#!/usr/bin/env python3
"""Validate the design corpus as a graph, and regenerate doc-map's graph section.

The 15 docs in `design/` are a connected system model: each doc's frontmatter `graph:`
block names the docs it is fed by and feeds, plus the GameState fields it reads and
writes. This script is the machine check on that model, replacing four obligations
CLAUDE.md previously asked a human to hold in their head.

    python3 docs/tools/check_design_graph.py           # check; exit 1 on any error
    python3 docs/tools/check_design_graph.py --doc-map  # also rewrite doc-map's graph block
    python3 docs/tools/check_design_graph.py --json     # dump the graph, check nothing

Errors fail the run. Warnings (asymmetric edges) are reported and do not: an asymmetry
is a design question for the human, not a defect the script may resolve on its own.

Paths resolve from this file's own location, so it does not care what the cwd is.
No third-party dependencies: the frontmatter subset used here is parsed directly.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parents[3]
DESIGN = REPO / "insignificant-game" / "design"
GAME_STATE = REPO / "insignificant-game" / "core" / "game_state.gd"
DOC_MAP = REPO / "docs" / "doc-map.html"

GRAPH_BEGIN = "<!-- @GRAPH:BEGIN (generated by insignificant-game/docs/tools/check_design_graph.py) -->"
GRAPH_END = "<!-- @GRAPH:END -->"

# Docs exempt from carrying a graph: block. The concept main page is an index over the
# system docs, not a system; README states corpus edit rules.
EXEMPT_STEMS = {"Insignificant", "README"}

# Directories doc-map covers with a single cluster row rather than one row per file.
CLUSTER_DIRS = {
    "insignificant-game/design": "14 setting docs",
    "docs/adr": "adr/ (sequential)",
    "docs/depandabot": "depandabot/ (dated)",
    "insignificant-game/assets/pipeline/review": "review/ (generated pick-gate pages)",
}

# Docs that exist for humans only and are deliberately absent from the registry.
DOC_MAP_EXEMPT = {"docs/Graph-Engineering-Athropic-Playbook.md"}


class Doc:
    __slots__ = ("stem", "path", "type", "fed_by", "feeds", "feeds_all", "res_in", "res_out", "code", "links")

    def __init__(self, path: pathlib.Path) -> None:
        self.path = path
        self.stem = path.stem
        self.type = ""
        self.fed_by: list[str] = []
        self.feeds: list[str] = []
        self.feeds_all = False
        self.res_in: list[str] = []
        self.res_out: list[str] = []
        self.code: list[str] = []
        self.links: set[str] = set()


def parse_frontmatter(text: str) -> tuple[str, str]:
    m = re.match(r"---\n(.*?)\n---\n", text, re.DOTALL)
    return (m.group(1), text[m.end():]) if m else ("", text)


def parse_list_block(fm: str, key: str, indent: str) -> list[str] | None:
    """Parse `key:` followed by `- item` lines, or an inline `key: [a, b]` / `key: []`."""
    inline = re.search(rf"^{indent}{key}:[ \t]*\[(.*?)\][ \t]*$", fm, re.MULTILINE)
    if inline:
        body = inline.group(1).strip()
        return [v.strip() for v in body.split(",") if v.strip()] if body else []
    block = re.search(rf"^{indent}{key}:[ \t]*$\n((?:{indent}[ \t]+- .*\n?)*)", fm, re.MULTILINE)
    if block:
        return [m.group(1).strip() for m in re.finditer(r"^\s+- (.*)$", block.group(1), re.MULTILINE)]
    return None


def strip_comment(v: str) -> str:
    return v.split("#", 1)[0].strip()


def wikilink_targets(body: str) -> set[str]:
    """Every [[target]] in the body, resolved past `\\|` table escapes, `|` aliases, `#anchors`."""
    out: set[str] = set()
    for raw in re.findall(r"\[\[([^\]]+)\]\]", body):
        target = re.split(r"\\\||\||#", raw, maxsplit=1)[0]
        target = target.replace("\\", "").strip()
        if target:
            out.add(target)
    return out


def load_docs() -> list[Doc]:
    docs = []
    for path in sorted(DESIGN.glob("*.md")):
        text = path.read_text(encoding="utf-8")
        fm, body = parse_frontmatter(text)
        doc = Doc(path)
        tm = re.search(r"^type:[ \t]*(.+)$", fm, re.MULTILINE)
        doc.type = tm.group(1).strip() if tm else ""
        doc.code = parse_list_block(fm, "code", "") or []
        gm = re.search(r"^graph:[ \t]*$\n((?:[ \t]+.*\n?)*)", fm, re.MULTILINE)
        if gm:
            g = gm.group(1)
            doc.fed_by = [strip_comment(v) for v in (parse_list_block(g, "fed_by", "  ") or [])]
            doc.feeds = [strip_comment(v) for v in (parse_list_block(g, "feeds", "  ") or [])]
            doc.res_in = [strip_comment(v) for v in (parse_list_block(g, "resources_in", "  ") or [])]
            doc.res_out = [strip_comment(v) for v in (parse_list_block(g, "resources_out", "  ") or [])]
            doc.feeds_all = bool(re.search(r"^  feeds_all:[ \t]*true", g, re.MULTILINE))
        doc.links = wikilink_targets(body)
        docs.append(doc)
    return docs


def game_state_fields() -> set[str]:
    if not GAME_STATE.is_file():
        return set()
    return set(re.findall(r"^var[ \t]+([A-Za-z_][A-Za-z0-9_]*)", GAME_STATE.read_text(encoding="utf-8"), re.MULTILINE))


def header_citations(gd: pathlib.Path) -> set[str]:
    """design/*.md stems cited in a .gd file's first 12 lines."""
    if not gd.is_file():
        return set()
    head = "".join(gd.read_text(encoding="utf-8", errors="replace").splitlines(True)[:12])
    return {pathlib.Path(m).stem for m in re.findall(r"design/([^\s,)`:]+\.md)", head)}


def repo_docs() -> list[str]:
    """Every doc-shaped file that doc-map is expected to account for."""
    out = []
    for pattern in ("docs/**/*.md", "docs/**/*.html", "insignificant-game/docs/**/*.md",
                    "insignificant-game/docs/**/*.html", "insignificant-game/design/*.md",
                    "insignificant-game/assets/pipeline/**/*.md", "insignificant-game/assets/pipeline/**/*.html",
                    "CLAUDE.md", "insignificant-game/CLAUDE.md"):
        for p in REPO.glob(pattern):
            if p.is_file():
                out.append(p.relative_to(REPO).as_posix())
    return sorted(set(out))


def check(docs: list[Doc]) -> tuple[list[str], list[str]]:
    errors: list[str] = []
    warnings: list[str] = []
    stems = {d.stem for d in docs}
    fields = game_state_fields()
    if not fields:
        errors.append(f"could not read GameState fields from {GAME_STATE.relative_to(REPO)}")
    by_stem = {d.stem: d in docs and d for d in docs}

    settings = [d for d in docs if d.stem not in EXEMPT_STEMS]

    for d in settings:
        rel = d.path.relative_to(REPO).as_posix()
        # E1 structure
        if d.type != "game-setting":
            errors.append(f"{rel}: expected `type: game-setting`, found {d.type or '(none)'!r}")
        fm, _ = parse_frontmatter(d.path.read_text(encoding="utf-8"))
        if not re.search(r"^graph:", fm, re.MULTILINE):
            errors.append(f"{rel}: missing a `graph:` frontmatter block")
            continue
        for key in ("fed_by", "feeds", "resources_in", "resources_out"):
            g = re.search(r"^graph:[ \t]*$\n((?:[ \t]+.*\n?)*)", fm, re.MULTILINE)
            if g and not re.search(rf"^  {key}:", g.group(1), re.MULTILINE):
                errors.append(f"{rel}: graph: block is missing `{key}:` (use `[]` to assert none)")
        # E2 node resolution
        for key, names in (("fed_by", d.fed_by), ("feeds", d.feeds)):
            for n in names:
                if n not in stems:
                    errors.append(f"{rel}: graph.{key} names {n!r}, which is not a doc in design/")
                elif n == d.stem:
                    errors.append(f"{rel}: graph.{key} names itself")
        # E3 resource resolution
        for key, names in (("resources_in", d.res_in), ("resources_out", d.res_out)):
            for n in names:
                if fields and n not in fields:
                    errors.append(f"{rel}: graph.{key} names {n!r}, not a field in core/game_state.gd")
        # W2 fully disconnected
        if not d.fed_by and not d.feeds:
            warnings.append(f"{rel}: declares no edges in either direction")

    # E4 wikilink resolution (all docs, including exempt ones)
    for d in docs:
        rel = d.path.relative_to(REPO).as_posix()
        for t in sorted(d.links):
            if t not in stems:
                errors.append(f"{rel}: wikilink [[{t}]] does not resolve to a doc in design/")

    # E5 every code: path exists; collect the doc -> file mapping
    cited_by: dict[str, set[str]] = {}
    for d in docs:
        rel = d.path.relative_to(REPO).as_posix()
        for c in d.code:
            if not (REPO / c).is_file():
                errors.append(f"{rel}: code: lists {c}, which does not exist")
                continue
            cited_by.setdefault(c, set()).add(d.stem)

    # E6 a header citation must be honoured by the doc it names (code -> doc direction).
    # This is the direction that catches real drift: a module claiming a doc that has no
    # idea it exists. The reverse is only a warning, because view/ and test/ files are
    # legitimately shared by several docs and the repo does not cite from all of them.
    for gd in sorted((REPO / "insignificant-game").rglob("*.gd")):
        if "addons" in gd.parts:
            continue
        rel = gd.relative_to(REPO).as_posix()
        for stem in sorted(header_citations(gd)):
            if stem not in stems:
                errors.append(f"{rel}: header cites design/{stem}.md, which does not exist")
            elif stem not in cited_by.get(rel, set()):
                errors.append(f"{rel}: header cites design/{stem}.md, but that doc's code: does not list it")

    # W3 a core/ module listed by a system doc should cite it back. Insignificant.md is the
    # concept index and maps to the driver files, not to a system, so it is exempt.
    for d in docs:
        if d.stem == "Insignificant":
            continue
        for c in d.code:
            if not c.startswith("insignificant-game/core/") or not c.endswith(".gd"):
                continue
            p = REPO / c
            if p.is_file() and d.stem not in header_citations(p):
                warnings.append(f"{c}: listed by {d.stem}.md, but its header does not cite that doc")

    # W1 reciprocity
    lookup = {d.stem: d for d in docs}
    for d in settings:
        rel = d.path.relative_to(REPO).as_posix()
        for target in d.feeds:
            other = lookup.get(target)
            if other and d.stem not in other.fed_by and not d.feeds_all:
                warnings.append(f"{rel}: feeds {target}, but {target}.md does not list it in fed_by")
        for source in d.fed_by:
            other = lookup.get(source)
            if other and d.stem not in other.feeds and not other.feeds_all:
                warnings.append(f"{rel}: fed_by {source}, but {source}.md does not list it in feeds")

    # E7 doc-map coverage
    if not DOC_MAP.is_file():
        errors.append(f"{DOC_MAP.relative_to(REPO)} not found")
    else:
        page = DOC_MAP.read_text(encoding="utf-8")
        for rel in repo_docs():
            if rel in DOC_MAP_EXEMPT:
                continue
            parent = rel.rsplit("/", 1)[0]
            if parent in CLUSTER_DIRS and CLUSTER_DIRS[parent] in page:
                continue
            if rel in page or rel.rsplit("/", 1)[-1] in page:
                continue
            errors.append(f"{rel}: no row in docs/doc-map.html (add a row, or extend a cluster)")

    return errors, warnings


def render_graph_block(docs: list[Doc]) -> str:
    settings = [d for d in docs if d.stem not in EXEMPT_STEMS]
    order = sorted(settings, key=lambda d: -(len(d.fed_by) + len(d.feeds)))
    rows = []
    for d in order:
        deg = len(d.fed_by) + len(d.feeds)
        role = "source" if not d.fed_by else ("sink" if not d.feeds else "")
        badge = f' <span class="chip">{role}</span>' if role else ""
        rows.append(
            f'    <tr><td>{d.stem}{badge}</td>'
            f"<td>{deg}</td>"
            f'<td>{"、".join(d.fed_by) or "—"}</td>'
            f'<td>{"、".join(d.feeds) or "—"}</td>'
            f'<td>{", ".join(sorted(set(d.res_in) | set(d.res_out))) or "—"}</td></tr>'
        )
    edges = sum(len(d.feeds) for d in settings)
    return "\n".join([
        GRAPH_BEGIN,
        '  <h3>System graph (generated) · design/ as a connected model</h3>',
        f'  <p class="sub">{len(settings)} system docs, {edges} declared feed edges. Each doc\'s '
        'frontmatter <code>graph:</code> block is the source; '
        '<code>insignificant-game/docs/tools/check_design_graph.py</code> checks reciprocity, '
        'resolves every name against <code>design/</code> and <code>core/game_state.gd</code>, and '
        'regenerates this table. Do not hand-edit between the markers.</p>',
        '  <div class="scroll">',
        '  <table>',
        '    <tr><th>System</th><th>Degree</th><th>Fed by</th><th>Feeds</th><th>GameState fields</th></tr>',
        *rows,
        '  </table>',
        '  </div>',
        GRAPH_END,
    ])


def write_doc_map(docs: list[Doc]) -> bool:
    page = DOC_MAP.read_text(encoding="utf-8")
    block = render_graph_block(docs)
    if GRAPH_BEGIN in page and GRAPH_END in page:
        new = re.sub(re.escape(GRAPH_BEGIN) + r".*?" + re.escape(GRAPH_END), lambda _: block, page, flags=re.DOTALL)
    else:
        anchor = '  <h2>Maintenance rules (the short version)</h2>'
        if anchor not in page:
            print("could not find the insertion anchor in doc-map.html", file=sys.stderr)
            return False
        new = page.replace(anchor, block + "\n\n" + anchor, 1)
    if new == page:
        return False
    DOC_MAP.write_text(new, encoding="utf-8")
    return True


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--doc-map", action="store_true", help="regenerate the graph block in docs/doc-map.html")
    ap.add_argument("--json", action="store_true", help="dump the parsed graph as JSON and exit")
    args = ap.parse_args()

    docs = load_docs()
    if args.json:
        print(json.dumps({
            d.stem: {"type": d.type, "fed_by": d.fed_by, "feeds": d.feeds, "feeds_all": d.feeds_all,
                     "resources_in": d.res_in, "resources_out": d.res_out, "code": d.code,
                     "links": sorted(d.links)}
            for d in docs
        }, ensure_ascii=False, indent=2))
        return 0

    errors, warnings = check(docs)
    settings = [d for d in docs if d.stem not in EXEMPT_STEMS]
    edges = sum(len(d.feeds) for d in settings)

    if args.doc_map:
        print("doc-map graph block updated" if write_doc_map(docs) else "doc-map graph block already current")

    print(f"design graph: {len(settings)} system docs, {edges} feed edges, "
          f"{sum(len(d.code) for d in docs)} code: mappings")
    for w in warnings:
        print(f"  WARN  {w}")
    for e in errors:
        print(f"  ERROR {e}")
    print(f"\n{len(errors)} error(s), {len(warnings)} warning(s)")
    if warnings and not errors:
        print("warnings are design questions for the human, not build failures")
    return 1 if errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
