# phase3_units_batch.py — Phase 3 class 2b: unit / fortification / enemy-tier sprites
# (cookbook §7), era lineage via img2img (cookbook §6) exactly like the buildings class:
# each line's start era is txt2img under style bible §2-§3; each later era is img2img from the
# SAME chain's previous era at DENOISE, so one seed = one coherent era chain and the human picks
# a whole lineage. Subjects follow 卡牌 部隊卡/工事卡的時代演化總表 and 戰鬥 敵方單位級別
# (inventory.md ids). Constants are imported by phase3_units_wave.py (the era-gated driver).
import os

SEEDS = [81, 82, 83, 84]
DENOISE = float(os.environ.get("P3U_DENOISE", "0.55"))  # override per-run when a parent artifact
# is too dominant for wording to beat (§14: naming a banned object reinforces it at cfg 1)
T2I = "workflows/krea2_lora_txt2img.json"
I2I = "workflows/krea2_lora_img2img.json"
LORA_ARGS = ["--lora", "Krea2_Moebius_LoRA.safetensors", "--lora-strength", "1.0"]
OUT = os.path.expanduser("~/ComfyUI-Shared/output/phase3-units")

# The units suffix is pilot-proven (§14 2026-07-14 v4 round); forts swap the class noun per
# style bible §3.
SUFFIX_UNIT = ", game unit sprite, side view, centered, isolated on a plain light gray background"
SUFFIX_FORT = ", game fortification sprite, side view, centered, isolated on a plain light gray background"
FORT_LINES = {"shield_wall", "anti_air"}


def suffix_for(line: str) -> str:
    return SUFFIX_FORT if line in FORT_LINES else SUFFIX_UNIT


# line -> [subject cores, one per era from the line's start era] (era forms: 卡牌 evolution
# tables / inventory.md; enemy tiers: 戰鬥 敵方單位級別, generic hostile look in a dark/rust
# palette so they read as the opposing side at battle scale). Subject rules from the buildings
# class + v4 units pilot (§14): figures are "identical" (uniformity), every subject carries an
# inherently colored element, every flat surface is occupied or absent (shield faces get painted
# rings, vehicle hulls/fuselages get a single white circle — never real-world insignia), religion
# carries the golden-tree motif, weapons are era-appropriate, no emotion nouns, no profession
# nouns that invite signage.
LINES = {
    "infantry": [
        "three identical tribal warriors in fur and hide swinging heavy wooden clubs, red war paint stripes on their arms",                                          # 棍棒戰團
        "exactly three identical spearmen standing in a tight rank, exactly three long spears total and no more, each of the three men gripping his own single spear in one hand and a round shield in the other, bronze helmets with red horsehair crests, the round shields each painted with a plain red ring",     # 長矛方陣 (round 2c: pinning one spear per hand still left a 4th ghost spearhead fused near the middle figure's helmet, unattached to any hand — the count-drift prior survived a per-figure pin, so state the total count explicitly up front as well ("exactly three... exactly three spears total") rather than only implying it per-figure)
        "three identical foot soldiers in chainmail and plain rounded open helmets, each raising one straight sword in the fist and gripping a kite shield in the other hand, the kite shields each painted with a plain red ring",  # 劍盾步兵 (v3: v2's "nothing else carried" NAMED the banned object and merely displaced e2's spear into a floating blade plus a curled hook overhead — fill both hands positively instead so no slot is left for it. v2: e2's spears rode down the chain as a shaft across every body, its crests as flame tongues)
        "three identical musketeer soldiers standing in a staggered line, each with both hands on his own musket held upright against his own shoulder with its fixed bayonet pointing straight up, plain dark blue wool coats with brass buttons over plain white waistcoats, tall black shako hats",      # 線列步兵 (v3: v2's defect was SELF-INFLICTED, not inherited — "a rank of" + "held level" put three identical horizontal barrels on one line and the model merged them into a single barrel spanning all three figures, at BOTH denoise 0.55 and 0.70 (so not parent-borne). Stagger the line and stand the muskets upright so three bayonets cannot be collinear. v2: e3 audit — fill both hands and the torso so e3's kite shield and mail have no slot to persist in)
        "three identical soldiers in olive drab uniforms and steel helmets with rifles, seated together inside an open-topped armored truck with a single white circle painted on its door",  # 摩托化步兵
        "three identical soldiers in bulky powered armor suits with glowing blue visor slits and oversized metal gauntlets",                                         # 動力裝甲兵
    ],
    "archers": [
        "three identical tribal hunters in hide tunics, each gripping a Y-shaped wooden slingshot forward at arm's length, the rear hand pinching a small leather pouch against the cheek with a round gray stone bulging inside it, two thick leather bands running taut from the pouch forward to the two fork tips, a small hide pouch of stones on each belt, red feathers tied in their hair",  # 投石手 (v4: v3 kept hanging the stone from the fork tips on a cord — anchor the pouch+stone at the rear hand/cheek and run the bands forward from it)
        "three identical archers in green tunics drawing tall wooden longbows, quivers of red-fletched arrows at their hips",                                        # 弓箭團
        "three identical crossbowmen in padded jackets and iron kettle helmets aiming heavy crossbows, red-fletched bolts in belt quivers",                          # 弩手連
        "in right-facing profile, three identical skirmisher soldiers all facing right and kneeling, in plain green jackets and soft black peaked caps, each aiming his own musket toward the right edge of the frame with both hands, the musket barrel having exactly two raised points along its entire length and no more, a flat rectangular lock plate at the breech and a single small triangular front sight blade at the muzzle tip, with the length between them perfectly smooth and bare, powder horns on red shoulder straps",                          # 火槍散兵 (round 2e: the counting-frame fix worked at the muzzle (exactly one front sight there, confirmed) but the redundant-nub prior relocated to the breech/lock area instead — the "no other raised point" clause named zero exceptions there, so the model filled it with a cluster of small nubs rather than rendering it truly bare. Extended the counting frame to name BOTH sanctioned raised points explicitly (lock plate at breech + front sight at muzzle, exactly two total) and pin the stretch between them as smooth. round 2d: "no curve anywhere along its length" redistributed one big curl into a repeating series of small hooked nubs along the whole barrel)
        "in right-facing profile, exactly two identical soldiers both facing right, in hooded leaf-camouflage cloaks, one kneeling aiming a long scoped rifle on a bipod toward the right edge of the frame, the other crouching beside him holding a brass spotting scope",     # 狙擊小隊 (pilot v2: appending "facing toward the right" as a suffix clause was not reliably obeyed — front-load the direction cue instead, the fix that worked elsewhere in this round)
        "in right-facing profile, two identical soldiers both facing right, each with a single solid white disc of one flat colour centered on his helmet front and no red or any other colour mixed into it, in gray armored suits, one shouldering a boxy missile launcher with the same solid all-white disc on its side and a glowing red targeting lens pointed toward the right, the other carrying a folded tripod radar dish",  # 精準飛彈組 (round 2e: the disc now appears reliably on both helmets (the repositioning fix worked) but renders half-white/half-red inside a black ring, likely the old red-chevron defect blending into the disc instead of disappearing — added an explicit "one flat colour... no red or any other colour mixed in" pin. The launcher's disc is still being dropped entirely despite being named right after the helmet discs in the same clause — added "the same solid all-white disc" as a more emphatic repeat directly at the launcher's own clause rather than relying on "the same disc" pronoun reference carrying over. round 2d: the disc requirement was DROPPED ENTIRELY on both helmets, replaced by an unprompted red chevron glyph — moved the disc clause earlier and trimmed negation bulk)
    ],
    "cavalry": [
        "three identical tribal riders in furs mounted on shaggy horned beasts with red cloth harnesses",                                                            # 馭獸騎手
        "a wooden war chariot pulled by two horses, a driver and a spearman aboard, a plain red pennant streaming from the chariot rail",                            # 戰車騎兵
        "exactly two identical armored knights in plain bare steel helmets, each gripping one raised lance in the fist and the reins in the other hand, each mounted on one horse draped in a plain red cloth caparison, the horses wearing smooth plain rounded steel face plates, the pair riding alone across open bare ground",  # 重裝騎士團 (v3: v2 fixed the horns 4/4 but every seed then filled the empty canvas with an unattached object — floating shield, standing sword, rump finials, a curled hook — and one grew a third horse; fill both hands and the count positively and name the ground bare. v2: "barded horses" pulled fantasy horned/spiked chamfrons 4/4)
        "in right-facing profile, two identical dragoon cavalrymen and their horses all facing right, galloping toward the right edge of the frame, bare-headed horses with plain leather bridles, each rider wearing a brass comb-crested helmet with a black horsehair mane, plain green coats with red cuffs, each rider gripping exactly one short flintlock carbine one-handed and angled toward the right, his other hand holding only the reins, both riders otherwise empty-handed",        # 龍騎兵 (round 2: direction now correct, but one rider held a second full long-arm braced two-handed in addition to the carbine — pin exactly one weapon per rider and name the other hand empty but for the reins)
        "a heavy battle tank standing alone on open bare ground with its long cannon barrel pointing toward the right, riveted armor plates, painted plain olive drab with a single white circle on the turret side",               # 坦克營 (player units face right)
        "three identical sleek unmanned tracked combat vehicles with sensor domes and glowing blue lens eyes, gunmetal hulls each with a single white circle on the side",  # 無人戰車群
    ],
    "engineers": [
        "three identical tribal laborers in hide tunics carrying log beams and stone hammers, coils of rope over their shoulders, red cloth headbands",              # 修路隊
        "three identical builders in leather aprons, one laying stone blocks with a trowel, one carrying a wooden beam with a plain red cloth strip tied around its end, one swinging a big wooden mallet",  # 築城匠 (v2: "survey stake" rendered as a striped range-pole/rocket with a glowing tip on all 4 seeds — remove the freestanding-pole slot, move the red carrier onto the beam)
        "three identical sappers in iron kettle helmets and brown leather jerkins pushing a tall standing shield wall of rough wooden planks that rests on the ground on two cart wheels fixed at its lower edge, one carrying a pickaxe, one a bundle of sticks, plain red shoulder sashes",  # 攻城工兵 (v3: v2's "mounted on two cart wheels" let the wheel detach — one seed floated it unattached between figures, another threaded it onto the carried beam; seat the wall on the ground with the wheels at its lower edge. v2: "mantlet" is an unknown noun — every seed rendered a supply cart instead, and bare "sappers ... iron helmets" pulled WW1 uniforms; name the object's form and pin the era costume)
        "three identical soldiers in plain gray uniforms with red collar trim and soft gray field caps, one carrying a short flat wooden plank bridge section tucked upright under one arm, one shouldering a shovel, one carrying a coil of wire in both hands",        # 工兵營 (v4: v3's "both of his own hands" did NOT stop the plank spanning two figures — a long horizontal object between identical figures merges no matter whose hands are named. Tuck it upright under one arm so it physically cannot reach a neighbour. v3: at denoise 0.70 the e3 standing plank wall cleared 4/4 with framing intact, but 2/4 then SHARED one long plank across two figures' shoulders — the same merge-identical-objects artifact as infantry e4, invariant to denoise. Shorten the plank, anchor it to one figure's own two hands, and give the other two figures their own two-handed loads. v2: e3 audit — name the headgear slot, and lay the planks flat on a shoulder so e3's tall wheeled plank wall cannot stand back up)
        "a yellow armored engineering vehicle with a bulldozer blade and a crane arm and a single flat solid white circle with no border and no ring on its hull side, two identical soldiers in olive uniforms and steel helmets walking beside it", # 機械化工兵 (round 2e: TWO consecutive attempts occupying the shoulder with a named object (epaulette loop) each bred a different colourful patch there anyway (first a red/white/blue flag, then a green/orange/blue chevron patch) — explicitly mentioning the shoulder/sleeve location at all seems to invite embellishment there regardless of what's named to occupy it. Chains 81 and 82 of this exact cell use this same bare wording (no sleeve mention whatsoever) and have never shown the defect — reverted to that proven-clean wording instead of continuing to describe the shoulder. round 2d: "plain unmarked sleeves" bred a full red/white/blue tricolor flag patch; round 2b: the hull circle grew a red border ring and a matching red/white patch bred on both soldiers' blank sleeves)
        "two identical soldiers in powered exo-frame suits with hydraulic arms, one carrying a folded bridge girder, one a heavy cutting torch with a glowing orange tip",  # 戰鬥工程隊
    ],
    "elite_forces": [
        "in right-facing profile, two identical royal guards both facing right, in gilded bronze armor and tall red-plumed helmets holding ornate halberds angled toward the right, plain purple cloaks",                                # 禁衛軍 (pilot v2: pilot v1 rendered left-facing on ALL FIVE eras of this line despite "facing toward the right" as a suffix clause — front-loading the direction as the sentence's opening cue and repeating it on the held weapon)
        "in right-facing profile, two identical temple knights both facing right, in white surcoats over chainmail holding greatswords raised toward the right, each surcoat bearing a single golden tree emblem",                       # 聖殿武士
        "in right-facing profile, two identical grenadier soldiers both facing right, in plain dark blue coats and tall black bearskin caps with red cords, each cap front bearing a plain white cloth cockade, each with a plain musket slung on a strap across his back, one holding a round black grenade with a short sputtering fuse, the other shielding that fuse with a cupped gloved hand",     # 擲彈兵 (v2: era-4 audit, MISSED in the first pass because this line starts at era 2 and the audit indexed [3]. Blank bearskin cap fronts bred real-world badges (gold bugle horn, cross pattee) 2/4, and an unprompted bayonet attracted the grenade's flame 2/4 — occupy the cap front with a cockade, give the weapon slot a plain slung musket, and put the fire only at the named fuse)
        "in right-facing profile, two identical commandos both facing right standing one behind the other, in black tactical armor with a single plain white circle on each chest plate, night-vision goggles with glowing green lenses, each with both hands on his own compact rifle held angled down toward the right",                             # 特種部隊
        "in right-facing profile, two identical cyborg super soldiers both facing right standing one behind the other, sleek chrome cybernetic arms and legs joined to armored torsos, each shoulder pauldron painted with a single solid unbroken white disc of flat colour with no notch, no crescent and no ring cut into or around it, a thin red accent line traces each side of the neck matching the suit's other red piping and nothing else on the neck, glowing blue eye implants and nothing else glowing anywhere on his body, each gripping one single heavy rifle with both hands and no second barrel, tube or weapon attached to it or resting anywhere near it",            # 生化超級士兵 (round 2f: the torso mark kept failing not because of wording but because of the POSE — both arms crossed forward gripping the raised rifle completely occlude the chest in this composition, so there was never a visible "torso" for the disc to land on; what reviewers kept flagging as a defective ring was actually the suit's own mechanical joint-socket motif (also seen at hip/knee/ankle) showing through at the shoulder, an unrelated design element. Moved the mark to the shoulder pauldron instead, which IS reliably visible in this pose and is a natural insignia location. Neck accent (redirected to match the suit's red piping) and rifle count (exactly one, no floating second barrel) are BOTH confirmed clean as of round 2e and unchanged here. pick-gate ruling: era-6 form is a human-scale cyborg super soldier, not a mech; eye-implant glow is a lens light and allowed, no glowing wires or materials)
    ],
    "artillery": [
        "a squat bronze bombard cannon on a timber sled aimed upward, stone cannonballs stacked beside it, a crewman in a padded jacket holding a glowing red linstock",   # 射石砲 (the line starts here at era 3: no ballista form, pick-gate ruling)
        "a field cannon with a bronze barrel resting on a two-wheeled carriage with large spoked wooden wheels, two identical gunners in plain dark blue uniforms each gripping a long bare wooden rammer staff with a cloth-wrapped head, a pyramid of black iron cannonballs",  # 野戰砲 (v3: v2's "plain unlit ... does not glow" NAMED the banned object and doubled it — one glowing tube became two, and the carriage reverted to e2's timber sled; describe the staff and the wheeled carriage positively, never mention light. v2: e2's "glowing red linstock" rode down as a glowing red cone, its padded jacket as a shearling flight jacket)
        "a tracked self-propelled howitzer standing alone on continuous steel track links with a long elevated gun barrel, painted plain olive drab with a single white circle on the hull side",                   # 自走砲 (v2: inheritance audit — the parent field cannon has spoked wooden wheels AND two gunners, so occupy the running-gear slot with track links and the crew slot with "standing alone")
        "a futuristic tracked railgun platform standing alone with twin long parallel magnetic rails elevated skyward, smooth matte gunmetal armor plates covered in fine recessed panel seam lines and rivets, every raised hull viewport, sensor dome and camera housing capped with a plain flat dark gray metal disc, a single white circle painted on the hull side",             # 電磁砲 (round 2d: naming the fixtures as "lens" and "light" and pinning each to "no glow" made things WORSE, not better — attempt 3 bred FIVE lit fixtures (a blue lens, an amber lens, and three amber lamps) where attempt 2 had only bred three, the same naming-primes-the-concept backfire seen on bomber's insignia problem. Diagnosed "lens"/"light" as words with too strong an inherent illumination association for a sci-fi vehicle sensor cluster, regardless of "no glow" qualifiers. Removed both words entirely — describe the components as solid metal-capped viewports/domes/housings, never call them a lens or a light. round 2c: naming the hull "uniformly unlit" fixed a seam light but bred three lit driving-lamp fixtures instead — the glow prior migrates to whatever named or unnamed fixture is available. round 2: the first de-glow wording still bred a glowing orange seam light on the hull — the same rifle-glow pattern seen on enemy_mid era 6)
    ],
    "bomber": [
        "in right-facing side profile, a long silver-gray rigid airship with its blunt nose pointing toward the right edge of the frame and its tapered tail with four cruciform fins toward the left, the entire hull and every fin surface covered edge to edge in a dense uniform grid of rivets and thin horizontal panel seams and nothing else, small round bombs falling from the gondola covered in the same dense rivet grid and nothing else",                           # 飛船轟炸隊 (round 2d: naming the banned marking types explicitly ("no roundel, no insignia, no squadron marking...") made the defect WORSE, not better — round 2c's wording produced full RAF-style roundels on both wings of the era-6 sibling, the single worst result this line has had across three generations. Diagnosed as the naming itself priming the model toward those exact concepts regardless of the "no". Drop every mention of the banned concept category entirely — no "roundel", "insignia", "marking", "badge", "stencil" words anywhere in the prompt — and rely purely on the positive rivet/panel-seam occupation with a bare "and nothing else" as the only exclusionary clause. round 2c: TWO rounds of an increasingly negated white-circle wording still grew a ring/border into a roundel — this line's military-aircraft insignia prior is unusually strong)
        "in right-facing side profile, a heavy four-engine propeller bomber aircraft with its nose and cockpit pointing toward the right edge of the frame and its tail toward the left, four propeller engines along its wings, painted a continuous plain olive drab colour, the entire fuselage, wings and tail fin covered edge to edge in a dense uniform grid of rivets and thin panel seams and nothing else, bomb bay doors open with falling bombs covered in the same dense rivet grid and nothing else", # 轟炸機聯隊 (round 2d: same fix as the airship — remove every named-marking-type word entirely, keep only the positive rivet/panel-seam occupation)
        "a black angular flying-wing stealth bomber seen from the side flying toward the right, its cockpit spine and every fuselage and wing surface a continuous plain matte black colour, the entire surface covered edge to edge in a dense uniform grid of recessed panel seams and rivets and nothing else, bomb bay open with a single guided bomb dropping covered in the same dense panel-seam grid and nothing else",                                  # 匿蹤轟炸機 (round 2d: same fix — remove every named-marking-type word entirely, keep only the positive panel-seam occupation. Engine glow removed per era-6 de-glow ruling)
    ],
    "holy_warriors": [
        "two identical musketeers in white coats standing close together, each with both hands on his own musket held upright against his own shoulder with the barrel pointing straight up, a single golden tree emblem on each chest, beside a standard bearer gripping the pole of a white banner showing a single large golden tree on one face of the cloth",  # 神權火槍旅 (the line's ONLY form: holy_warriors exist only at era 4 and are dismissed at era 5, pick-gate ruling. Wording kept from the picked s81 cell: upright muskets narrow the silhouette, break barrel collinearity and pin the tree to one cloth face)
    ],
    "privateers": [
        "three identical bandits in dark leather jerkins and red head scarves, each gripping a short curved sword with exactly one blade total in one hand and no other weapon, exactly one of the three bandits carrying a small closed brown loot sack over his shoulder and the other two carrying nothing on their shoulders",  # 盜匪團 (round 2e: the sack-count fix worked cleanly (confirmed exactly 1 sack), but exposed a NEW count-drift defect on the sword: all three bandits gripped TWO full curved blades fused to one hilt instead of one. "exactly one... sword" pins the weapon count but not the blade count on that weapon, so the model can still double the blade itself. Added an explicit "exactly one blade total" clause. round 2d: a fresh reseed drifted to TWO sacks instead of one — switched to an explicit count clause, the same fix pattern that worked for infantry's ghost-spear defect. round 2: one figure dual-wielded two drawn cutlasses instead of the prompted one; pick-gate ruling: privateers are now era-3 bandits / era-4 thieves / era-5 hackers, dismissed at era 6; the sack stays closed so no coin-spill slot opens)
        "three identical thieves in dark hooded coats and red neck scarves, one carrying a closed brass-cornered strongbox under one arm, one holding a crowbar, one holding a small hooded lantern",                      # 竊賊團 (every figure's hands are filled positively)
        "three identical hackers in dark hooded jackets and red neck scarves, each sitting cross-legged with an open laptop on his lap, each laptop's outer lid a plain unmarked dark surface with no logo or brand mark, the laptop screens each showing a single large plain coin symbol",  # 網路駭客 (round 2: the blank laptop lid bred a real Apple logo on all three units, a trademark risk — name the lid plain and unmarked. The screen still carries the sanctioned coin symbol so no text can breed there)
    ],
    "shield_wall": [
        "a row of tall rough wooden plank shields lashed together with rope into a standing wall, spear tips poking over the top, red cloth strips tied at the joints",  # 木盾牆
        "a tight freestanding wall of overlapping round bronze shields each embossed with a plain raised ring pattern, a clean level top edge",                            # 盾陣 (pick-gate ruling: no spears popping out of the shield wall; the top edge is named clean the way e3's parapet line is, so nothing bristles from it)
        "a stone battlement wall segment with a crenellated top and arrow slits, an unbroken smooth masonry face and a clean level parapet line, a plain red pennant on a corner pole",  # 城垛 (v3: v2's "no arrows and no blades anywhere" NAMED the banned object and made it worse — 4 arrows became 7 projecting blades plus sparks; describe the intact surface positively and never name the weapon. v2: e2's "spears bristling between them" rode down as arrows driven through the stone heads-outward)
        "a chest-high wall of stacked burlap sandbags in even rows with wooden support posts, the sandbag surface soft and rounded throughout, a rifle resting on the top edge",                                                   # 沙包工事 (v2: e3 audit — name the surface soft and rounded so e3's crenellated stone masonry has no slot)
        "a tall fence of taut electrified steel wire mesh strung between dark metal posts on a row of low concrete base blocks, each post topped with a single rounded metal cap holding one white ceramic insulator flush against it, a plain red stripe painted across the base blocks",                         # 電網 (round 2: an unnamed post-top let a thin metal sliver float free beside the insulator hardware — cap the post top with a named rounded fitting so nothing is left loose)
        "a segment of modular barrier wall of smooth matte gray fiber-reinforced polymer panels bolted to a steel frame, deployable metal struts at its base, a plain red stripe painted across its lower edge",                  # 複合裝甲牆 (pick-gate ruling: FRP panels, real material with smooth matte resin finish; no glowing seam lights, era-6 de-glow ruling)
    ],
    "anti_air": [
        "a slanted shelter roof of plain overlapping brown and tan dry raw hides on stout timber posts, several old spent arrows stuck upright in the hides, bare trampled earth below",  # 擋箭棚 (v3: v2's "arrows stuck in" kept splashing orange impact liquid on chain 84 (3 of that chain's 4 fails) — drain the energy: dry hides, old spent arrows. v2: v1's blank hide surfaces bred whimsy creatures/glyphs on every seed — name the hides plain, the earth bare)
        "a tall timber arrow tower with a roofed shooting platform and wooden hoardings, a red cloth strip tied to a corner post",                                   # 箭樓
        "a round stone defense tower with machicolations, its top an open flat circle of bare stone paving under clear open sky, a mounted ballista aimed skyward on it loaded with a plain wooden bolt",  # 城防塔 (v3: v2's "no roof and no tiles and no timber shelter" NAMED the banned object and the tiled roof came back on chain 84; describe the open stone top positively and never mention roofs. v2: e2's roofed shooting platform rode down as a tiled-roof timber pavilion, the bolt as glowing cyan energy)
        "an anti-aircraft flak cannon with exactly one single long barrel angled skyward on a cross-shaped steel mount resting directly on flat bare ground, a ring gunsight, stacked shell crates beside it, painted plain olive drab",  # 高射砲 (v3: twin parallel barrels off one breech twice on chain 82 — pin the barrel count positively. v2: e3 audit — e3 is a round stone tower; seat the mount on bare ground so no masonry base can persist under it)
        "a tracked vehicle painted plain olive drab with a single white circle on the hull, carrying four white surface-to-air missiles on rails angled skyward",    # 防空飛彈
        "a boxy laser interception turret on a rotating gimbal mount facing toward the right, a single large circular optical lens aperture aimed skyward toward the upper right, two small camera pods mounted beside the aperture, matte olive drab armor housing with a single solid unbroken white disc of flat colour painted on its side, the disc a complete circle with no notch and no crescent cut into it",  # 雷射攔截網 (pilot v2: pilot v1's "single white circle" rendered as a Pac-Man-style crescent with a wedge bitten out — the sanctioned-mark occupant migrated its own shape; name the disc solid, unbroken and complete)
    ],
    "enemy_weak": [
        "a lone levy warrior in a plain dark wool tunic cut in one straight piece with a single smooth hem with no notches or points anywhere along its edge, belted at the waist with a plain leather strap, laced leather sandals, a simple leather cap, gripping a wooden spear with both hands, a plain orange cloth band tied around one upper arm",                                         # 弱 e1 (round 2e: the material change (hide->wool) fixed the shoulders and side seams completely, but the hem/front-slit still showed small triangular notches — likely because "stitched hem" itself invited a decorative whip-stitch V-pattern along the edge. Dropped "stitched" and named the hem "smooth with no notches or points" instead, isolating the fix to just the remaining problem area without touching what already works. round 2d: switched material hide->wool and dropped "tribal" after the construction-description fix alone did not suppress the tattered look)
        "a lone militia spearman in a plain dark linen tunic and a simple leather helmet, holding a spear in one hand and a small round wooden shield painted with a plain orange ring in the other",                                       # 弱 e2
        "a lone levy crossbowman in a plain dark padded gambeson and a simple iron cap, aiming a light crossbow, a plain orange cloth band tied around one upper arm",                                           # 弱 e3
        "a lone militiaman in a plain dark brown coat and a soft cap, both hands on his own single musket held upright against his shoulder, the musket's muzzle end a single round barrel tip capped with one plain front sight nub, a long bayonet blade mounted flush against the barrel in one thin metal socket ring and no other stud, tube or second barrel anywhere beside it, a rolled gray blanket strapped diagonally across his back and a plain canvas ammunition pouch at his belt, a plain orange cloth armband of unbroken solid colour on one upper sleeve",                                                 # 弱 e4 (round 2e: pinning "no second tube or barrel" without ever mentioning a bayonet still bred a duplicate-tube shape at the muzzle — the model renders a bayonet at the muzzle unprompted regardless (present on every seed of this cell so far) and its mounting hardware fills the "unnamed slot" with a wide second cylinder when given no explicit shape to follow. Since the bayonet keeps appearing anyway, name it explicitly and give its mount a specific, deliberately thin shape (a socket ring) instead of leaving it to the model's default. round 2d: the blanket/pouch fix killed the floating-second-gun defect on the body, but chain-83 grew a NEW duplicate-barrel defect right at the muzzle itself)
        "a lone reservist soldier in a plain dark gray uniform and a soft field cap, both hands on his own rifle held angled down, a plain orange armband of unbroken solid colour on one upper sleeve",                                                     # 弱 e5
        "a lone volunteer soldier standing full-length from head to boots in side profile, in a plain dark gray jacket with a few plain dull metal studs on the chest and an orange visor over his eyes, both hands on his own compact energy carbine held angled down",                                                 # 弱 e6 (round 2: this cell rendered as a cropped bust/portrait instead of the full-body template — pin the framing explicitly; the chest keeps the proven stud occupant that starved the glyph prior; visor light is allowed, no glowing wires)
    ],
    "enemy_mid": [
        "two identical disciplined warriors in matching dark hide-and-bone armor, each holding one stone-tipped spear in his own fist and a hide shield painted with a plain orange ring",                                         # 中 e1 (pick-gate ruling: the mid tier is PROFESSIONAL MILITARY — matched kit, dark palette, orange accents)
        "two identical professional soldiers in matching dark iron scale armor and plain dark helmets, each with one short sword in his own fist and a round shield painted with a plain orange ring",                    # 中 e2
        "two identical men-at-arms in blackened chainmail and dark kettle helmets, each holding one poleaxe upright in his own hands, kite shields each painted with a single smooth closed orange ring with a perfectly continuous curve and no hook, no tail and no notch anywhere on it, slung on their backs",  # 中 e3 (round 2b: the ring grew a small hook/serif at its upper edge, a shape-embellishment variant of the ring-to-roundel prior — pin the curve as continuous with no hook named explicitly)
        "two identical line soldiers in matching dark gray uniforms and black shakos standing in a staggered line, each with both hands on his own musket held upright against his own shoulder, a plain orange band painted around each shako",                   # 中 e4 (staggered line + upright muskets: the proven infantry-e4 geometry that keeps identical barrels from merging)
        "two identical soldiers in matching dark combat uniforms, armor vests and helmets, standing one behind the other, each with both hands on his own rifle held angled down, a plain orange armband of unbroken solid colour on each upper sleeve",                                          # 中 e5
        "two identical soldiers in matte black powered vests with glowing orange visor slits, a single plain orange band painted across each shoulder pad, standing one behind the other, each with both hands on his own solid matte black heavy rifle held angled down, the rifle body plain metal with no lit parts",                                         # 中 e6 (pilot v2: pilot v1's rifle grew an unprompted glowing orange bar along its body — the visor+shoulder glow budget migrated onto the weapon; name the rifle body plain matte metal so it carries no light)
    ],
    "enemy_hard": [
        "a towering elite champion in heavy dark bone-and-hide armor swinging a massive stone maul with both hands, a plain orange stripe painted across his chest plate",                               # 硬 e1 (pick-gate ruling: the hard tier is ELITE MILITARY — heavy disciplined kit, dark palette, orange accents)
        "a towering elite champion in heavy dark bronze plate armor holding a huge two-handed cleaver blade, a tower shield embossed with a plain raised ring pattern standing at his side",                         # 硬 e2
        "a towering elite knight in polished black plate armor with a smooth rounded greathelm, both hands swinging a massive two-handed flail, a dark cape",                                               # 硬 e3 (smooth helm keeps the disciplined elite read)
        "a hulking soldier in a heavy dark iron cuirass painted with a single plain orange stripe and a smooth rounded steel helmet, both hands carrying a hand-cranked multi-barrel gun, ammunition belts across his chest",                                # 硬 e4 (the cuirass occupant switches to the ENEMY orange stripe, not the player white circle; the blank-pauldron insignia lesson stands)
        "a heavy dark battle tank freshly painted in glossy showroom-new black enamel, every hull and turret plate smooth and bright with clean crisp reflections, the road wheels, drive sprockets and track links a clean dark gunmetal metal with a smooth factory finish, a single flat solid orange stripe of one plain colour and no other colour painted on the turret",                                   # 硬 e5 (round 2d: the "glossy showroom-new" fix cleared the hull/turret finish but left the road wheels and drive sprockets unnamed — confirmed rust-brown coloring specifically on the sprocket teeth/hub on both chains, the one component this line's wording never addressed. Real battle-tank photos almost always show weathered dark metal running gear even on freshly-painted hulls, so that's an unusually strong, narrowly-scoped prior; name the wheels/sprockets/track links explicitly and pin them to a clean gunmetal finish, purely positive language (no "rust" or "corrosion" words) per the same lesson that fixed the hull. round 2c: THREE consecutive negation-based attempts naming the absence of rust/corrosion/weathering all still bred rust — per the positive-slot rule, negating a banned attribute reinforces it rather than removing it)
        "a towering black combat mech with glowing orange eye sensors, massive clawed arms and missile pods on its shoulders, every armor plate and pod housing a plain unmarked matte black surface with no lettering and no stencilled text anywhere",                                       # 硬 e6 (round 2b: white stencilled lettering rendered on a shoulder missile-pod housing — name every plate explicitly unmarked and free of text. eye-sensor glow is a lens light and allowed; no wires)
    ],
}

# lines that unlock later start their chain at this era (txt2img root there). Pick-gate round 1
# design rulings: artillery starts at era 3 (no ballista form), holy_warriors exists only at
# era 4 (dismissed at era 5), privateers span eras 3-5 (dismissed at era 6).
START_ERA = {"elite_forces": 2, "artillery": 3, "holy_warriors": 4, "privateers": 3, "bomber": 4}
