# phase3_units_batch.py — Phase 3 class 2b: unit / fortification / enemy-tier sprites
# (cookbook §7), era lineage via img2img (cookbook §6) exactly like the buildings class:
# each line's start era is txt2img under style bible §2-§3; each later era is img2img from the
# SAME chain's previous era at DENOISE, so one seed = one coherent era chain and the human picks
# a whole lineage. Subjects follow 卡牌 部隊卡/工事卡的時代演化總表 and 戰鬥 敵方單位級別
# (inventory.md ids). Constants are imported by phase3_units_wave.py (the era-gated driver).
import os

SEEDS = [81, 82, 83, 84]
DENOISE = float(os.environ.get("P3U_DENOISE", "0.55"))  # override per-run when a parent artifact
# is too dominant for wording to beat (§14: naming a banned object reinforces it at cfg 1)
T2I = "workflows/krea2_lora_txt2img.json"
I2I = "workflows/krea2_lora_img2img.json"
LORA_ARGS = ["--lora", "Krea2_Moebius_LoRA.safetensors", "--lora-strength", "1.0"]
OUT = os.path.expanduser("~/ComfyUI-Shared/output/phase3-units")

# The units suffix is pilot-proven (§14 2026-07-14 v4 round); forts swap the class noun per
# style bible §3.
SUFFIX_UNIT = ", game unit sprite, side view, centered, isolated on a plain light gray background"
SUFFIX_FORT = ", game fortification sprite, side view, centered, isolated on a plain light gray background"
FORT_LINES = {"shield_wall", "anti_air"}


def suffix_for(line: str) -> str:
    return SUFFIX_FORT if line in FORT_LINES else SUFFIX_UNIT


# line -> [subject cores, one per era from the line's start era] (era forms: 卡牌 evolution
# tables / inventory.md; enemy tiers: 戰鬥 敵方單位級別, generic hostile look in a dark/rust
# palette so they read as the opposing side at battle scale). Subject rules from the buildings
# class + v4 units pilot (§14): figures are "identical" (uniformity), every subject carries an
# inherently colored element, every flat surface is occupied or absent (shield faces get painted
# rings, vehicle hulls/fuselages get a single white circle — never real-world insignia), religion
# carries the golden-tree motif, weapons are era-appropriate, no emotion nouns, no profession
# nouns that invite signage.
LINES = {
    "infantry": [
        "three identical tribal warriors in fur and hide swinging heavy wooden clubs, red war paint stripes on their arms",                                          # 棍棒戰團
        "in right-facing full-body profile, three identical spearmen standing in a tight rank, each of the three men gripping his own single spear in one hand and a round shield in the other, bronze helmets with red horsehair crests",     # round 3: human-authored replacement prompt from pickgate review
        "in right-facing full-body profile, three identical foot soldiers in chainmail and open helmets with swords raised",  # round 3: human-authored replacement prompt from pickgate review
        "in right-facing full-body profile, three identical musketeer soldiers standing in a staggered line, aiming on musket with its fixed bayonet pointing straight up, plain dark blue wool coats with brass buttons over plain white waistcoats, tall black shako hats",      # round 3: human-authored replacement prompt from pickgate review
        "in right-facing full-body profile, three identical soldiers in olive drab uniforms and steel helmets with rifles",  # round 3: human-authored replacement prompt from pickgate review
        "in right-facing full-body profile, three identical soldiers in bulky powered armor suits with infrared visor slits and oversized metal gauntlets",                                         # round 3: human-authored replacement prompt from pickgate review
    ],
    "archers": [
        "three identical tribal hunters in hide tunics, each gripping a Y-shaped wooden slingshot forward at arm's length, the rear hand pinching a small leather pouch against the cheek with a round gray stone bulging inside it, two thick leather bands running taut from the pouch forward to the two fork tips, a small hide pouch of stones on each belt, red feathers tied in their hair",  # 投石手 (v4: v3 kept hanging the stone from the fork tips on a cord — anchor the pouch+stone at the rear hand/cheek and run the bands forward from it)
        "three identical archers in green tunics drawing tall wooden longbows, quivers of red-fletched arrows at their hips",                                        # 弓箭團
        "three identical crossbowmen in padded jackets and iron kettle helmets aiming heavy crossbows, red-fletched bolts in belt quivers",                          # 弩手連
        "in right-facing full-body profile, three identical skirmisher soldiers all facing right, in plain jackets and soft black peaked caps, each aiming his own musket toward the right edge of the frame with both hands",                          # round 3b: human review found 4 figures rendered for 3 guns on the round-3 kneeling composition -- dropped kneeling pose and the gun counting-frame detail entirely per human instruction
        "in right-facing profile, exactly two identical soldiers both facing right, in hooded leaf-camouflage cloaks, one kneeling aiming a long scoped rifle on a bipod toward the right edge of the frame, the other crouching beside him holding a brass spotting scope",     # 狙擊小隊 (pilot v2: appending "facing toward the right" as a suffix clause was not reliably obeyed — front-load the direction cue instead, the fix that worked elsewhere in this round)
        "in right-facing full-body profile, two identical soldiers both facing right, wearing helmets, in gray armored suits with a clean unmarked look and no stains, marks or streaks of colour anywhere on the fabric, one shouldering a boxy missile launcher with the same solid all-white disc on its side and a glowing red targeting lens pointed toward the right, the other carrying a folded tripod radar dish",  # round 3b: human review found an unprompted yellow paint-splash blob plus red streaks on the coat -- added explicit clean/unmarked-fabric clause per human instruction
    ],
    "cavalry": [
        "three identical tribal riders in furs mounted on shaggy horned beasts with red cloth harnesses",                                                            # 馭獸騎手
        "a wooden war chariot pulled by two horses, a driver and a spearman aboard, a plain red pennant streaming from the chariot rail",                            # 戰車騎兵
        "exactly two identical armored knights in plain bare steel helmets, each gripping one raised lance in the fist and the reins in the other hand, each mounted on one horse draped in a plain red cloth caparison, the horses wearing smooth plain rounded steel face plates, the pair riding alone across open bare ground",  # 重裝騎士團 (v3: v2 fixed the horns 4/4 but every seed then filled the empty canvas with an unattached object — floating shield, standing sword, rump finials, a curled hook — and one grew a third horse; fill both hands and the count positively and name the ground bare. v2: "barded horses" pulled fantasy horned/spiked chamfrons 4/4)
        "in right-facing profile, two identical dragoon cavalrymen and their horses all facing right, galloping toward the right edge of the frame, bare-headed horses with plain leather bridles, each rider wearing a brass comb-crested helmet with a black horsehair mane, plain green coats with red cuffs, each rider gripping exactly one short flintlock carbine one-handed and angled toward the right, his other hand holding only the reins, both riders otherwise empty-handed",        # 龍騎兵 (round 2: direction now correct, but one rider held a second full long-arm braced two-handed in addition to the carbine — pin exactly one weapon per rider and name the other hand empty but for the reins)
        "a heavy battle tank standing alone on open bare ground with its long cannon barrel pointing toward the right, riveted armor plates",               # round 3: human-authored replacement prompt from pickgate review
        "a sleek unmanned tracked combat vehicle with a sensor dome, a gunmetal hull with a fine repeating grid of recessed panel seam lines and no other surface detail, no roundel, no insignia, no squadron marking, no badge, no lettering and no stencil anywhere",  # round 3: human-authored replacement prompt from pickgate review
    ],
    "engineers": [
        "three identical tribal laborers in hide tunics carrying log beams and stone hammers, coils of rope over their shoulders, red cloth headbands",              # 修路隊
        "three identical builders in leather aprons, one laying stone blocks with a trowel, one carrying a wooden beam with a plain red cloth strip tied around its end, one swinging a big wooden mallet",  # 築城匠 (v2: "survey stake" rendered as a striped range-pole/rocket with a glowing tip on all 4 seeds — remove the freestanding-pole slot, move the red carrier onto the beam)
        "in right-facing full-body profile, three identical sappers in iron kettle helmets and brown leather jerkins pushing a tall standing shield wall of rough wooden planks that rests on the ground on cart fixed at its lower edge, one carrying a pickaxe, one a bundle of sticks, plain red shoulder sashes",  # round 3: human-authored replacement prompt from pickgate review
        "three identical soldiers in plain gray uniforms with red collar trim and soft gray field caps, one carrying a short flat wooden plank bridge section tucked upright under one arm, one shouldering a shovel, one carrying a coil of wire in both hands",        # 工兵營 (v4: v3's "both of his own hands" did NOT stop the plank spanning two figures — a long horizontal object between identical figures merges no matter whose hands are named. Tuck it upright under one arm so it physically cannot reach a neighbour. v3: at denoise 0.70 the e3 standing plank wall cleared 4/4 with framing intact, but 2/4 then SHARED one long plank across two figures' shoulders — the same merge-identical-objects artifact as infantry e4, invariant to denoise. Shorten the plank, anchor it to one figure's own two hands, and give the other two figures their own two-handed loads. v2: e3 audit — name the headgear slot, and lay the planks flat on a shoulder so e3's tall wheeled plank wall cannot stand back up)
        "in right-facing full-body profile, a yellow armored engineering vehicle with a bulldozer blade and a crane arm and a single white circle on its hull side, two identical soldiers sit inside the vehicle in olive uniforms and steel helmets with head out", # round 3: human-authored replacement prompt from pickgate review
        "two identical soldiers in powered exo-frame suits with hydraulic arms, one carrying a folded bridge girder, one a heavy cutting torch with a glowing orange tip",  # 戰鬥工程隊
    ],
    "elite_forces": [
        "in right-facing profile, two identical royal guards both facing right, in gilded bronze armor and tall red-plumed helmets holding ornate halberds angled toward the right, plain purple cloaks",                                # 禁衛軍 (pilot v2: pilot v1 rendered left-facing on ALL FIVE eras of this line despite "facing toward the right" as a suffix clause — front-loading the direction as the sentence's opening cue and repeating it on the held weapon)
        "in right-facing full-body profile, two identical temple knights both facing right, in white surcoats over chainmail holding greatswords raised toward the right, each surcoat bearing a single golden tree emblem",                       # round 3: human-authored replacement prompt from pickgate review
        "in right-facing full-body profile, two identical grenadier soldiers, in plain dark blue coats and helmets, each with a plain musket slung on a strap across his back, one holding a round dark-green grenade with a short sputtering fuse, the other shielding that fuse with a cupped gloved hand",     # round 3: human-authored replacement prompt from pickgate review
        "in right-facing full-body profile, two commandos standing one behind the other, in black tactical armor, night-vision goggles with green lenses, each with both hands on his own compact rifle held angled down toward the right",                             # round 3: human-authored replacement prompt from pickgate review
        "in right-facing full-body profile, two identical cyborg super soldiers standing one behind the other, sleek chrome cybernetic arms and legs joined to armored torsos, night-vision eyes implants, each with both hands on his own heavy rifle",            # round 3: human-authored replacement prompt from pickgate review
    ],
    "artillery": [
        "a squat bronze bombard cannon on a timber sled aimed upward, stone cannonballs stacked beside it, a crewman in a padded jacket holding a glowing red linstock",   # 射石砲 (the line starts here at era 3: no ballista form, pick-gate ruling)
        "a field cannon with a bronze barrel resting on a two-wheeled carriage with large spoked wooden wheels, two identical gunners in plain dark blue uniforms each gripping a long bare wooden rammer staff with a cloth-wrapped head, a pyramid of black iron cannonballs",  # 野戰砲 (v3: v2's "plain unlit ... does not glow" NAMED the banned object and doubled it — one glowing tube became two, and the carriage reverted to e2's timber sled; describe the staff and the wheeled carriage positively, never mention light. v2: e2's "glowing red linstock" rode down as a glowing red cone, its padded jacket as a shearling flight jacket)
        "in right-facing full-body profile, a tracked self-propelled howitzer on continuous steel track links with a long elevated gun barrel, painted plain olive drab with a single white circle on the hull side, a crew member standing on a wooden ladder against the hull holding a cleaning rod",                   # 自走砲 (round 3: human review reintroduced a crew figure via ladder+cleaning-rod, matching e2's crewed composition; dropped "standing alone" since it now contradicts the added crew member, added explicit "full-body profile" framing cue)
        "a futuristic tracked railgun platform standing alone with twin long parallel magnetic rails elevated skyward, smooth matte gunmetal armor plates covered in fine recessed panel seam lines and rivets, every raised hull viewport, sensor dome and camera housing capped with a plain flat dark gray metal disc, a single white circle painted on the hull side",             # 電磁砲 (round 2d: naming the fixtures as "lens" and "light" and pinning each to "no glow" made things WORSE, not better — attempt 3 bred FIVE lit fixtures (a blue lens, an amber lens, and three amber lamps) where attempt 2 had only bred three, the same naming-primes-the-concept backfire seen on bomber's insignia problem. Diagnosed "lens"/"light" as words with too strong an inherent illumination association for a sci-fi vehicle sensor cluster, regardless of "no glow" qualifiers. Removed both words entirely — describe the components as solid metal-capped viewports/domes/housings, never call them a lens or a light. round 2c: naming the hull "uniformly unlit" fixed a seam light but bred three lit driving-lamp fixtures instead — the glow prior migrates to whatever named or unnamed fixture is available. round 2: the first de-glow wording still bred a glowing orange seam light on the hull — the same rifle-glow pattern seen on enemy_mid era 6)
    ],
    "bomber": [
        "in right-facing side profile, a long silver-gray rigid airship with its blunt nose pointing toward the right edge of the frame and its tapered tail with four cruciform fins toward the left, the hull and fins covered edge to edge in a fine repeating grid of rivets and thin horizontal panel seams, no roundel, no insignia, no squadron marking, no tail flash, no lettering and no stencil anywhere on the craft, one small round bombs falling from the gondola with the same plain rivet-and-panel surface and no marking of any kind",                           # round 3: human-authored replacement prompt from pickgate review
        "in right-facing side profile, a heavy four-engine propeller bomber aircraft with its nose and cockpit pointing toward the right edge of the frame and its tail toward the left, four propeller engines along its wings, painted a continuous plain olive drab colour with a fine repeating grid of rivets and thin panel seam lines covering the fuselage and tail fin edge to edge, no roundel, no insignia, no squadron marking, no tail flash, no lettering and no stencil anywhere on the aircraft", # round 3: human-authored replacement prompt from pickgate review
        "a black angular flying-wing stealth bomber seen from the side flying toward the right, its cockpit spine and every fuselage and wing surface a continuous plain matte black colour with a fine repeating grid of recessed panel seam lines and no other surface detail, no roundel, no insignia, no squadron marking, no badge, no lettering and no stencil anywhere on the aircraft",                                  # round 3: human-authored replacement prompt from pickgate review
    ],
    "holy_warriors": [
        "in right-facing full-body profile, two identical musketeers in white coats standing close together, each with both hands on his own musket held upright against his own shoulder with the barrel pointing straight up, a single golden tree emblem on each chest",  # round 3: human-authored replacement prompt from pickgate review
    ],
    "privateers": [
        "in right-facing full-body profile, a lone bandit in a dark leather jerkin, gripping a short curved sword, carrying a small closed brown loot sack over his shoulder",  # round 3: human-authored replacement prompt from pickgate review
        "in right-facing full-body profile, a lone thief in a dark hooded coat and neck scarf, carrying a brass-cornered suitcase under his arm",                      # round 3: human-authored replacement prompt from pickgate review
        "in right-facing full-body profile, a lone cyber hacker in a suit, walking and carrying a laptop in his hands, the laptop's outer lid a plain unmarked metallic surface with no logo or brand mark",  # round 3: human-authored replacement prompt from pickgate review
    ],
    "shield_wall": [
        "a 30 degree towards left row of tall rough wooden plank shields lashed together with rope into a standing wall, spear tips poking over the top, red cloth strips tied at the joints",  # round 3: human-authored replacement prompt from pickgate review
        "a 30 degree towards left tight freestanding wall of overlapping kite shields each embossed with a plain raised ring pattern, a clean level top edge",                            # round 3: human-authored replacement prompt from pickgate review
        "a 30 degree towards left stone battlement wall segment with a crenellated top and arrow slits, an unbroken smooth masonry face and a clean level parapet line",  # round 3: human-authored replacement prompt from pickgate review
        "a 30 degree towards left chest-high wall of stacked burlap sandbags in even rows with wooden support posts, the sandbag surface soft and rounded throughout",                                                   # round 3: human-authored replacement prompt from pickgate review
        "a 30 degree towards left tall fence of taut electrified steel wire mesh strung between dark metal posts on a row of low concrete base blocks, each post topped with a single rounded metal cap holding one white ceramic insulator flush against it",                         # round 3: human-authored replacement prompt from pickgate review
        "a 30 degree towards left segment of modular barrier wall of smooth matte gray fiber-reinforced polymer panels bolted to a steel frame, deployable metal struts at its base",                  # round 3: human-authored replacement prompt from pickgate review
    ],
    "anti_air": [
        "a slanted shelter roof of plain overlapping brown and tan dry raw hides on stout timber posts, several old spent arrows stuck upright in the hides, bare trampled earth below",  # 擋箭棚 (v3: v2's "arrows stuck in" kept splashing orange impact liquid on chain 84 (3 of that chain's 4 fails) — drain the energy: dry hides, old spent arrows. v2: v1's blank hide surfaces bred whimsy creatures/glyphs on every seed — name the hides plain, the earth bare)
        "a tall timber arrow tower with a roofed shooting platform and wooden hoardings, a red cloth strip tied to a corner post",                                   # 箭樓
        "a round stone defense tower with machicolations, its top an open flat circle of bare stone paving under clear open sky, a mounted ballista aimed skyward on it loaded with a plain wooden bolt",  # 城防塔 (v3: v2's "no roof and no tiles and no timber shelter" NAMED the banned object and the tiled roof came back on chain 84; describe the open stone top positively and never mention roofs. v2: e2's roofed shooting platform rode down as a tiled-roof timber pavilion, the bolt as glowing cyan energy)
        "an anti-aircraft flak cannon with exactly one single long barrel angled skyward on a cross-shaped steel mount resting directly on flat bare ground, a ring gunsight, stacked shell crates beside it, painted plain olive drab",  # 高射砲 (v3: twin parallel barrels off one breech twice on chain 82 — pin the barrel count positively. v2: e3 audit — e3 is a round stone tower; seat the mount on bare ground so no masonry base can persist under it)
        "a tracked vehicle painted plain olive drab with a single white circle on the hull, carrying four white surface-to-air missiles on rails angled skyward",    # 防空飛彈
        "a boxy laser interception turret on a rotating gimbal mount facing toward the right, a single large circular optical lens aperture aimed skyward toward the upper right, two small camera pods mounted beside the aperture, matte olive drab armor housing with a single solid unbroken white disc of flat colour painted on its side, the disc a complete circle with no notch and no crescent cut into it",  # 雷射攔截網 (pilot v2: pilot v1's "single white circle" rendered as a Pac-Man-style crescent with a wedge bitten out — the sanctioned-mark occupant migrated its own shape; name the disc solid, unbroken and complete)
    ],
    "enemy_weak": [
        "in left-facing full-body profile, a lone tribal levy warrior in a plain dark hide tunic and a simple leather cap, gripping a wooden spear with both hands",                                         # round 3: human-authored replacement prompt from pickgate review
        "in left-facing full-body profile, a lone militia spearman in a plain dark linen tunic and a simple leather helmet, holding a spear in one hand and a small round wooden shield painted",                                       # round 3: human-authored replacement prompt from pickgate review
        "in left-facing full-body profile, a lone levy crossbowman in a plain dark padded gambeson and a simple iron cap, aiming a light crossbow",                                           # round 3: human-authored replacement prompt from pickgate review
        "in left-facing full-body profile, a lone militiaman in a plain dark brown coat and a soft cap, aiming musket against his shoulder, the musket's muzzle end a single round barrel tip capped with one plain front sight nub, a long bayonet blade mounted flush against the barrel in one thin metal socket ring and no other stud, tube or second barrel anywhere beside it, a rolled gray blanket strapped diagonally across his back and a plain canvas ammunition pouch at his belt",                                                 # round 3: human-authored replacement prompt from pickgate review
        "in left-facing full-body profile, a lone reservist soldier in a plain dark gray uniform and a soft field cap, both hands on his own rifle held angled down",                                                     # round 3: human-authored replacement prompt from pickgate review
        "in left-facing full-body profile, a lone volunteer soldier standing full-length from head to boots in side profile, in a plain dark gray jacket with a few plain dull metal studs on the chest and an compact visor over his eyes, both hands on his own compact energy carbine held angled down",                                                 # round 3: human-authored replacement prompt from pickgate review
    ],
    "enemy_mid": [
        "in left-facing full-body profile, two identical disciplined warriors in matching dark hide-and-bone armor, each holding one stone-tipped spear in his own fist",                                         # round 3: human-authored replacement prompt from pickgate review
        "in left-facing full-body profile, two identical professional soldiers in matching dark iron scale armor and plain dark helmets, each with one short sword in his own fist and a round shield",                    # round 3: human-authored replacement prompt from pickgate review
        "in left-facing full-body profile, two identical men-at-arms in blackened chainmail and dark kettle helmets, each holding one poleaxe upright in his own hands, kite shields each",  # round 3: human-authored replacement prompt from pickgate review
        "in left-facing full-body profile, two identical line soldiers in matching dark gray uniforms and black shakos, aiming left",                   # round 3: human-authored replacement prompt from pickgate review
        "two identical soldiers in matching dark combat uniforms, armor vests and helmets, standing one behind the other, each with both hands on his own rifle held angled down, a plain orange armband of unbroken solid colour on each upper sleeve",                                          # 中 e5
        "in left-facing full-body profile, two identical soldiers in matte black powered vests, standing one behind the other, each with both hands on his own solid matte black heavy rifle held angled down, the rifle body plain metal with no lit parts",                                         # round 3: human-authored replacement prompt from pickgate review
    ],
    "enemy_hard": [
        "in left-facing full-body profile, a towering elite champion in heavy dark bone-and-hide armor swinging a massive stone maul with both hands",                               # round 3: human-authored replacement prompt from pickgate review
        "a towering elite champion in heavy dark bronze plate armor holding a huge two-handed cleaver blade, a tower shield embossed with a plain raised ring pattern standing at his side",                         # 硬 e2
        "a towering elite knight in polished black plate armor with a smooth rounded greathelm, both hands swinging a massive two-handed flail, a dark cape",                                               # 硬 e3 (smooth helm keeps the disciplined elite read)
        "in left-facing full-body profile, a hulking soldier in a heavy dark iron cuirass and a smooth rounded steel helmet, both hands carrying a hand-cranked multi-barrel gun, ammunition belts across his chest",                                # round 3: human-authored replacement prompt from pickgate review
        "a heavy dark battle tank freshly painted in glossy showroom-new black enamel, every hull and turret plate smooth and bright with clean crisp reflections, a single flat solid orange stripe of one plain colour and no other colour painted on the turret",                                   # round 3: human-authored replacement prompt from pickgate review
        "a towering black combat mech with glowing orange eye sensors, massive clawed arms and missile pods on its shoulders, every armor plate and pod housing a plain unmarked matte black surface with no lettering and no stencilled text anywhere",                                       # 硬 e6 (round 2b: white stencilled lettering rendered on a shoulder missile-pod housing — name every plate explicitly unmarked and free of text. eye-sensor glow is a lens light and allowed; no wires)
    ],
}

# lines that unlock later start their chain at this era (txt2img root there). Pick-gate round 1
# design rulings: artillery starts at era 3 (no ballista form), holy_warriors exists only at
# era 4 (dismissed at era 5), privateers span eras 3-5 (dismissed at era 6).
START_ERA = {"elite_forces": 2, "artillery": 3, "holy_warriors": 4, "privateers": 3, "bomber": 4}
